### ISSUE TITLE
Merging back to master

### ISSUE THREAD

**Issue by argenos** [HBRS-RM/advanced-welding-test-djordje_and_pradheep#6]
I will grade you based on your contributions to this repository, not what is in your own forks. 
Work in progress that is currently in your fork should have a corresponding open pull request.

This is related to #3, so only merge back code that is not breaking your build and keep your pull requests open until you've fixed any issues you have.

**Comment by argenos** [comment]
There is nothing on your master branch!

**Comment by DjoleMNE** [comment]
Final code merged into master branch
